// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Translation translation
//
// swagger:model Translation
type Translation struct {

	// confirmed
	Confirmed bool `json:"confirmed,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// down votes
	DownVotes int64 `json:"downVotes,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// up votes
	UpVotes int64 `json:"upVotes,omitempty"`
}

// Validate validates this translation
func (m *Translation) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Translation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Translation) UnmarshalBinary(b []byte) error {
	var res Translation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
