// Code generated by go-swagger; DO NOT EDIT.

package translation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetTranslationsParams creates a new GetTranslationsParams object
// with the default values initialized.
func NewGetTranslationsParams() *GetTranslationsParams {
	var ()
	return &GetTranslationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTranslationsParamsWithTimeout creates a new GetTranslationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTranslationsParamsWithTimeout(timeout time.Duration) *GetTranslationsParams {
	var ()
	return &GetTranslationsParams{

		timeout: timeout,
	}
}

// NewGetTranslationsParamsWithContext creates a new GetTranslationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTranslationsParamsWithContext(ctx context.Context) *GetTranslationsParams {
	var ()
	return &GetTranslationsParams{

		Context: ctx,
	}
}

// NewGetTranslationsParamsWithHTTPClient creates a new GetTranslationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTranslationsParamsWithHTTPClient(client *http.Client) *GetTranslationsParams {
	var ()
	return &GetTranslationsParams{
		HTTPClient: client,
	}
}

/*GetTranslationsParams contains all the parameters to send to the API endpoint
for the get translations operation typically these are written to a http.Request
*/
type GetTranslationsParams struct {

	/*ContinuationToken
	  continuation token to get next translations

	*/
	ContinuationToken *string
	/*Language
	  language

	*/
	Language string
	/*Word
	  word id

	*/
	Word int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get translations params
func (o *GetTranslationsParams) WithTimeout(timeout time.Duration) *GetTranslationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get translations params
func (o *GetTranslationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get translations params
func (o *GetTranslationsParams) WithContext(ctx context.Context) *GetTranslationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get translations params
func (o *GetTranslationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get translations params
func (o *GetTranslationsParams) WithHTTPClient(client *http.Client) *GetTranslationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get translations params
func (o *GetTranslationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContinuationToken adds the continuationToken to the get translations params
func (o *GetTranslationsParams) WithContinuationToken(continuationToken *string) *GetTranslationsParams {
	o.SetContinuationToken(continuationToken)
	return o
}

// SetContinuationToken adds the continuationToken to the get translations params
func (o *GetTranslationsParams) SetContinuationToken(continuationToken *string) {
	o.ContinuationToken = continuationToken
}

// WithLanguage adds the language to the get translations params
func (o *GetTranslationsParams) WithLanguage(language string) *GetTranslationsParams {
	o.SetLanguage(language)
	return o
}

// SetLanguage adds the language to the get translations params
func (o *GetTranslationsParams) SetLanguage(language string) {
	o.Language = language
}

// WithWord adds the word to the get translations params
func (o *GetTranslationsParams) WithWord(word int64) *GetTranslationsParams {
	o.SetWord(word)
	return o
}

// SetWord adds the word to the get translations params
func (o *GetTranslationsParams) SetWord(word int64) {
	o.Word = word
}

// WriteToRequest writes these params to a swagger request
func (o *GetTranslationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContinuationToken != nil {

		// header param continuation-token
		if err := r.SetHeaderParam("continuation-token", *o.ContinuationToken); err != nil {
			return err
		}

	}

	// path param language
	if err := r.SetPathParam("language", o.Language); err != nil {
		return err
	}

	// path param word
	if err := r.SetPathParam("word", swag.FormatInt64(o.Word)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
