// Code generated by go-swagger; DO NOT EDIT.

package translation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/idena-network/idena-translation/test/models"
)

// GetConfirmedTranslationReader is a Reader for the GetConfirmedTranslation structure.
type GetConfirmedTranslationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConfirmedTranslationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetConfirmedTranslationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetConfirmedTranslationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetConfirmedTranslationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetConfirmedTranslationOK creates a GetConfirmedTranslationOK with default headers values
func NewGetConfirmedTranslationOK() *GetConfirmedTranslationOK {
	return &GetConfirmedTranslationOK{}
}

/*GetConfirmedTranslationOK handles this case with default header values.

OK
*/
type GetConfirmedTranslationOK struct {
	Payload *models.GetConfirmedTranslationResponse
}

func (o *GetConfirmedTranslationOK) Error() string {
	return fmt.Sprintf("[GET /word/{word}/language/{language}/confirmed-translation][%d] getConfirmedTranslationOK  %+v", 200, o.Payload)
}

func (o *GetConfirmedTranslationOK) GetPayload() *models.GetConfirmedTranslationResponse {
	return o.Payload
}

func (o *GetConfirmedTranslationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetConfirmedTranslationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetConfirmedTranslationBadRequest creates a GetConfirmedTranslationBadRequest with default headers values
func NewGetConfirmedTranslationBadRequest() *GetConfirmedTranslationBadRequest {
	return &GetConfirmedTranslationBadRequest{}
}

/*GetConfirmedTranslationBadRequest handles this case with default header values.

Bad Request
*/
type GetConfirmedTranslationBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *GetConfirmedTranslationBadRequest) Error() string {
	return fmt.Sprintf("[GET /word/{word}/language/{language}/confirmed-translation][%d] getConfirmedTranslationBadRequest  %+v", 400, o.Payload)
}

func (o *GetConfirmedTranslationBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetConfirmedTranslationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetConfirmedTranslationInternalServerError creates a GetConfirmedTranslationInternalServerError with default headers values
func NewGetConfirmedTranslationInternalServerError() *GetConfirmedTranslationInternalServerError {
	return &GetConfirmedTranslationInternalServerError{}
}

/*GetConfirmedTranslationInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetConfirmedTranslationInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetConfirmedTranslationInternalServerError) Error() string {
	return fmt.Sprintf("[GET /word/{word}/language/{language}/confirmed-translation][%d] getConfirmedTranslationInternalServerError  %+v", 500, o.Payload)
}

func (o *GetConfirmedTranslationInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetConfirmedTranslationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
