// Code generated by go-swagger; DO NOT EDIT.

package translation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new translation API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for translation API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetConfirmedTranslation(params *GetConfirmedTranslationParams) (*GetConfirmedTranslationOK, error)

	GetTranslations(params *GetTranslationsParams) (*GetTranslationsOK, error)

	SubmitTranslation(params *SubmitTranslationParams) (*SubmitTranslationOK, error)

	Vote(params *VoteParams) (*VoteOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetConfirmedTranslation gets confirmed translation
*/
func (a *Client) GetConfirmedTranslation(params *GetConfirmedTranslationParams) (*GetConfirmedTranslationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetConfirmedTranslationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getConfirmedTranslation",
		Method:             "GET",
		PathPattern:        "/word/{word}/language/{language}/confirmed-translation",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetConfirmedTranslationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetConfirmedTranslationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getConfirmedTranslation: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetTranslations gets translations sorted by rating
*/
func (a *Client) GetTranslations(params *GetTranslationsParams) (*GetTranslationsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTranslationsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getTranslations",
		Method:             "GET",
		PathPattern:        "/word/{word}/language/{language}/translations",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTranslationsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetTranslationsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getTranslations: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  SubmitTranslation creates or update translation
*/
func (a *Client) SubmitTranslation(params *SubmitTranslationParams) (*SubmitTranslationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSubmitTranslationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "submitTranslation",
		Method:             "POST",
		PathPattern:        "/translation",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &SubmitTranslationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SubmitTranslationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for submitTranslation: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  Vote votes for or against translation
*/
func (a *Client) Vote(params *VoteParams) (*VoteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewVoteParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "vote",
		Method:             "POST",
		PathPattern:        "/vote",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &VoteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*VoteOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for vote: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
