// Code generated by go-swagger; DO NOT EDIT.

package translation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/idena-network/idena-translation/test/models"
)

// NewVoteParams creates a new VoteParams object
// with the default values initialized.
func NewVoteParams() *VoteParams {
	var ()
	return &VoteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVoteParamsWithTimeout creates a new VoteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVoteParamsWithTimeout(timeout time.Duration) *VoteParams {
	var ()
	return &VoteParams{

		timeout: timeout,
	}
}

// NewVoteParamsWithContext creates a new VoteParams object
// with the default values initialized, and the ability to set a context for a request
func NewVoteParamsWithContext(ctx context.Context) *VoteParams {
	var ()
	return &VoteParams{

		Context: ctx,
	}
}

// NewVoteParamsWithHTTPClient creates a new VoteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVoteParamsWithHTTPClient(client *http.Client) *VoteParams {
	var ()
	return &VoteParams{
		HTTPClient: client,
	}
}

/*VoteParams contains all the parameters to send to the API endpoint
for the vote operation typically these are written to a http.Request
*/
type VoteParams struct {

	/*Vote
	  vote details

	*/
	Vote *models.VoteRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the vote params
func (o *VoteParams) WithTimeout(timeout time.Duration) *VoteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vote params
func (o *VoteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vote params
func (o *VoteParams) WithContext(ctx context.Context) *VoteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vote params
func (o *VoteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vote params
func (o *VoteParams) WithHTTPClient(client *http.Client) *VoteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vote params
func (o *VoteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVote adds the vote to the vote params
func (o *VoteParams) WithVote(vote *models.VoteRequest) *VoteParams {
	o.SetVote(vote)
	return o
}

// SetVote adds the vote to the vote params
func (o *VoteParams) SetVote(vote *models.VoteRequest) {
	o.Vote = vote
}

// WriteToRequest writes these params to a swagger request
func (o *VoteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Vote != nil {
		if err := r.SetBodyParam(o.Vote); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
